apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: TOCHANGE
  namespace: TOCHANGE
spec:
  interval: 1m
  chart:
    spec:
      chart: prometheus
      sourceRef:
        name: prometheus-community
        namespace: default
        kind: HelmRepository
  values:
    server:
      ingress:
        enabled: true
        ingressClassName: traefik
        host: TOCHANGE
